import { lastElement } from "./q1";
import { secondlElement } from "./q2";
import { kthElement } from "./q3-";
import { numberOfElement } from "./q4";
import { reverseList } from "./q5";
import { palindromeArray } from "./q6";
import { identical } from "./q8";
import { packCon } from "./q9";
import { encode } from "./q10";
// import { encodee } from "./q11";
// import { decode } from "./q12";
import { duplicate } from "./q14";
import { duplicateNtimes } from "./q15";
import { dropNthElement } from "./q16";
import { splitTheList } from "./q17";
import { extract } from "./q18";
import { rotateNLeft } from "./q19";
import { dropNthElements } from "./q20";
import { insert } from "./q21";
import { range } from "./q22";
import { selectRandom } from "./q23";
import { shuffle } from "./q25";

const group = ["a", "b", "c", "d", "e", "f", "g", "h"];
const array = [1, 2, 2, 1];
let arr = [5, 5, 5, 2, 2, 2, 2, 2, 9, 4, 5, 5, 5];
const arry = ["k", "T", "h", "a", "i", "s"];

console.log("last element:", lastElement(group));
console.log("second last element:", secondlElement(group));
console.log(" kthelement:", kthElement(group, 3));
console.log(" numberOfElement:", numberOfElement(group));
console.log(" reverseList:", reverseList(group));
console.log(" palindromeArray:", palindromeArray(array));
console.log("identical :", identical(arr));
console.log(" packCon:", packCon(arr));
console.log(" encode:", encode(arr));
console.log(" encodee:", encode(arr));
console.log(" decode:", encode(arr));
console.log(" duplicate:", duplicate(array));
console.log(" duplicateNtimes:", duplicateNtimes(array, 3));
console.log(" dropNthElement:", dropNthElement(arry, 3));
console.log("splitTheList :", splitTheList(array, 2));
console.log("extract :", extract(group, 2, 6));
console.log("rotateNLeft :", rotateNLeft(group, 3));
console.log(" dropNthElements:", dropNthElements(arr, 3));
console.log(" insert:", insert(arr, 3, "o"));
console.log("range", range(4, 10));
console.log("selectRandom", selectRandom(arr, 5));
console.log("shuffle", arr);
